[workspace]
members = ["sysfs_lib", "sysfs_macros"]

[package]
name = "sysfs"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
sysfs_lib = { path = "./sysfs_lib" }
sysfs_macros = { path = "./sysfs_macros" }
